name: Build, Publish, and Deploy Project to MonsterASP.NET

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          
      - name: Publish Application
        run: dotnet publish PointOfSale/PointOfSale.csproj --configuration Release --no-build --output release

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: release
          target-path: ""
      